/**
 * Hebrew UI copy (interface chrome), centralized so wording can be reviewed without touching components.
 * Question and answer copy is NOT here: it is structured data in src/data/content/question_copy_he.json.
 */
export const copy = {
  appTitle: "StudyMatch — השוואת תוכניות לימוד",
  appDescription: "כלי שעוזר להבין איזו תוכנית לימוד מתאימה לך יותר, ולמה.",
  brand: "COLMAN StudyMatch",
  steps: {
    select: "בחירת תוכניות",
    questions: "שאלות",
    result: "תוצאה",
  },
  select: {
    heading: "אילו תוכניות לימוד אתם שוקלים?",
    instructions: "בחרו 2–3 תוכניות להשוואה.",
    selectedCount: (count: number, max: number) => `נבחרו ${count} מתוך ${max}`,
    selectedLabel: "נבחרה",
    start: "התחילו בהשוואה",
  },
  questions: {
    comparing: "משווים בין:",
    progress: (questionNumber: number) => `שאלה ${questionNumber}`,
    typicalLength: (min: number, max: number) => `בדרך כלל ${min}–${max} שאלות`,
    optionsLabel: "אפשרויות תשובה",
    back: "חזרה",
    restart: "התחלה מחדש",
  },
  result: {
    whyTitle: "למה קיבלתם את התוצאה הזאת?",
    evidenceMixedLabel: "מצד שני",
    mirrorTitle: "זה נשמע כמוכם?",
    mirrorYes: "כן, זה נשמע כמוני",
    mirrorNo: "לא בדיוק",
    mirrorYesThanks: "מעולה. אפשר להמשיך לקרוא למטה.",
    mirrorNoThanks:
      "תודה. התוצאה מבוססת על התשובות שלכם, ואפשר תמיד לחזור לשאלה האחרונה ולענות אחרת, או להתחיל השוואה חדשה.",
    nearTieTopTag: "נטייה קלה לכיוון הזה",
    nearTieSecondTag: "קרובה מאוד",
    tradeoffTitle: "ההתלבטות האמיתית שלכם",
    tradeoffVersus: "מול",
    decidedBy: "מה שהטה את הכף בתשובות שלכם:",
    counter: "ומנגד, גם זה עניין אתכם:",
    sharedYearTitle: "חשוב לדעת:",
    learnTitle: "מה תלמדו",
    learnNote: "הנושאים והקורסים לפי המידע הרשמי באתר המכללה; התוכנית עשויה להשתנות.",
    realWorldTitle: "איך זה נראה בעולם האמיתי?",
    realWorldChallenge: "דוגמה לאתגר:",
    careersTitle: "כיוונים אפשריים בהמשך",
    careersNote: "לפי המידע הרשמי באתר המכללה. אין בכך הבטחה לתעסוקה.",
    realityTitle: "כדאי לדעת לפני שמחליטים",
    secondaryTitle: "ומה לגבי האפשרות השנייה?",
    secondaryFits: "מה בתשובות שלכם מתאים גם לאפשרות הזאת:",
    secondaryDifference: "ההבדל המרכזי ביניהן:",
    alternativesTitle: "האפשרויות הקרובות יותר",
    whyColmanTitle: "למה ללמוד את זה דווקא במכללה למינהל?",
    ctaTitle: "מה עושים עכשיו?",
    admission: "לבדיקת תנאי הקבלה",
    programPage: "לעמוד התוכנית באתר המכללה",
    compareFocused: "השוואה ממוקדת בין שתי האפשרויות הקרובות",
    compareNew: "השוואה חדשה",
    exploreOthers: "לבדיקת תוכניות אחרות",
    opensNewTab: "נפתח בלשונית חדשה",
    notYouTitle: "לא מרגיש לכם נכון?",
    notYouBody: "אפשר לחזור לשאלה האחרונה ולשנות תשובה, או להתחיל השוואה מחדש.",
    backToQuestion: "חזרה לשאלה האחרונה",
    restart: "התחלה מחדש",
  },
  v2: {
    appTitle: "StudyMatch — לאיזה פרויקט הייתם מצטרפים?",
    appDescription: "בוחרים פרויקט שמושך אתכם ומגלים איזה כיוון לימודים נשמע הכי קרוב.",
    stepsLabel: "שלבי המסע",
    steps: { select: "פרויקטים", questions: "שאלות", result: "תוצאה" },
    discover: {
      projectsLabel: "פרויקטים לבחירה",
      selectedCount: (count: number) => `נבחרו ${count} מתוך 2`,
      selectedLabel: "נבחר",
      maxReached: "אפשר לבחור עד שני פרויקטים. כדי להחליף, בטלו בחירה קיימת.",
      start: "בואו נתחיל",
    },
    questions: {
      progressTitle: "בונים את הכיוון שלכם",
      back: "חזרה",
      restart: "התחלה מחדש",
      gapTitle: "לא הצלחנו להמשיך",
      gapBody: "משהו בבחירות האלה לא הסתדר לנו. אפשר לחזור צעד אחורה או להתחיל מחדש עם פרויקטים אחרים.",
    },
  },
} as const;
