/**
 * Analytics vocabulary. Source of truth: docs/ANALYTICS.md.
 * Semantics and payload conventions: docs/ANALYTICS.md. Events are emitted through FunnelTracker (funnelTracker.ts).
 */

export const ANALYTICS_EVENTS = [
  "degree_compare_view",
  "degree_selected",
  "comparison_started",
  "question_view",
  "question_answer",
  "adaptive_branch_selected",
  "tie_breaker_view",
  "comparison_completed",
  "recommended_program",
  "secondary_program_view",
  "mirror_response",
  "curriculum_click",
  "career_click",
  "reality_check_view",
  "admission_click",
  "restart_comparison",
  "change_program",
  "advisor_cta_click",
  "whatsapp_click",
  "lead_submit",
  "comparison_share",
  // V2 career-project discovery (THI-16). Additive: V1 events above are unchanged.
  "career_project_discovery_view",
  "career_project_selected",
  "career_project_deselected",
  "career_project_selection_completed",
  "precision_module_handoff",
  "studymatch_result_view",
  "official_program_click",
  "discovery_back",
  // V2 lead form (THI-16 review pass). Metadata only: never a field value.
  "lead_form_view",
  "lead_form_submit",
  "lead_form_success",
  "lead_form_error",
  // V3 (UX redesign). Additive; every V3 event carries flow_version "v3".
  "studymatch_landing_view",
  "studymatch_start",
  "question_continue",
  "result_program_click",
  "result_contact_click",
  "result_all_programs_click",
  "result_detail_expand",
  // V3 world-led discovery (DEC-034). V2 keeps the career_project_* events; V3 never emits them.
  "career_world_discovery_view",
  "career_world_selected",
  "career_world_deselected",
  "career_world_selection_completed",
  // V4 dual-entry discovery (DEC-035). Every V4 event also carries flow_version "v4" and entry_mode.
  "discovery_method_view",
  "discovery_method_selected",
] as const;

export type AnalyticsEventName = (typeof ANALYTICS_EVENTS)[number];

export const ANALYTICS_PARAMS = [
  "comparison_id",
  "program_id",
  "result_kind",
  "leading_program",
  "program_1",
  "program_2",
  "program_3",
  "selected_program_count",
  "recommended_program",
  "secondary_program",
  "main_decision_pair",
  "fit_classification",
  "comparison_cluster",
  "question_id",
  "question_type",
  "answer_id",
  "branch_id",
  "question_index",
  "questions_answered",
  "is_tie_breaker",
  "mirror_response",
  "utm_source",
  "utm_medium",
  "utm_campaign",
  "utm_content",
  "utm_term",
  // V2 (THI-16)
  "flow_version",
  "project_id",
  "project_ids",
  "project_count_available",
  "selected_project_count",
  "selection_count",
  "selection_position",
  "question_mode",
  "question_kind",
  "is_generated_focus",
  "focus_program_count",
  "is_neutral",
  "module_id",
  "seeded_answer_count",
  "alternative_programs",
  "scored_answer_count",
  "total_answer_count",
  "link_role",
  "error_type",
  "cta_position",
  "detail_section",
  "world_id",
  "world_ids",
  "selected_world_count",
  "world_count_available",
  "entry_mode",
] as const;

export type AnalyticsParamName = (typeof ANALYTICS_PARAMS)[number];

/** Only stable IDs and scalar values — no free-text candidate responses (privacy, ANALYTICS.md). */
export type AnalyticsParams = Partial<Record<AnalyticsParamName, string | number | boolean>>;
